// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hanfhsbxaxdcdwkfwsqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhbmZoc2J4YXhkY2R3a2Z3c3FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MDUwNTcsImV4cCI6MjA2OTQ4MTA1N30.xnlQRo1qBTwQiYbG0ZnIlUkj05kckC6iULXPqq3mrAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});